# Railway Configuration for XMTP Mini App Monorepo

[build]
builder = "NIXPACKS"

# Frontend Service - Next.js Application
[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "yarn build"

[services.deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100

# Backend Service - XMTP Agent
[[services]]
name = "backend"
source = "backend"

[services.deploy]
startCommand = "yarn start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

