# Railway Configuration - Single Service Deployment
# Frontend (Next.js) + Backend (XMTP Agent) run together

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
